### ISSUE TITLE
Make Training Portion of May 6th Bi-Weekly Available 

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#115]
Make Training Portion (last half) of May 6th Bi-Weekly Available for reply.

Can you also make a recommendation of where this replay should be posted? FINOS.org page? Docs site?

**Comment by aitana16** [comment]
hi @brooklynrob @maoo please find the recording here https://www.finos.org/hubfs/FINOS/2020%20Video%20Uploads/FINOS%20-%20Open%20Source%20Fundamentals%20-%20Part%201%20-%2006%20May%2020.mp4 
huge shoutout to Grizz @grizzwolf for the great work. Please let me know if you have any comments

**Comment by maoo** [comment]
Great content! No strong opinions on where this should go, but I guess either www.finos.org or alloy.finos.org (one of the two). I'll defer to @aitana16 and @grizzwolf

**Comment by aitana16** [comment]
The recording was posted to https://github.com/finos/alloy#1-review-the-existing-materials, closing this issue now.
