### ISSUE TITLE
Test build and deploy works in open source environment for SDLC

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#129]
Test build and deploy works in open source environment for SDLC

**Comment by brooklynrob** [comment]
According to @maoo on 2020-10-5, there is one pull request, pull request number 17, that needs to be merged and this issue can be completed. @gs-bracej do you agree?

**Comment by gs-bracej** [comment]
I've merged that PR, but it looks like we're hitting another Sonar issue now.

**Comment by maoo** [comment]
Delivered:
- Run build
- Run tests
- Build artifacts
- Deploy to Sonatype snapshots
- Integrate with WhiteSource
- Integrate with SonarCloud

**Comment by gs-bracej** [comment]
Thank you very much!
