### ISSUE TITLE
Test build and deploy works in open source environment for Studio

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#132]
Test build and deploy works in open source environment for Studio

**Comment by maoo** [comment]
Build docs are available at https://github.com/finos/alloy/tree/build/build-sample

Note! This is expected to be a time-consuming effort, due to the high amount of build permutations and complexity of the build process.

**Comment by brooklynrob** [comment]
Per @maoo, and along the lines of his comment above, Mao has recommended we allocate two weeks for this task. Implication is that we need to allocate at least two weeks between Code Uplift completing (https://github.com/finos/alloy/milestone/9) and the actual flip switch to make the code public (https://github.com/finos/alloy/issues/147, which rolls up to https://github.com/finos/alloy/milestone/6). CC @gs-bracej @beekemarie

**Comment by maoo** [comment]
Studio module build is green! Closing issue

**Comment by brooklynrob** [comment]
@gs-bracej -- Just double checking ... from the GS side this is considered 100% done and we are good to go for open sourcing? (CC @beekemarie @maoo)

**Comment by gs-bracej** [comment]
Yes. We have a stretch goal of publishing to NPM, but we have a separate issue for that so lets close this one.
