### ISSUE TITLE
Choose New Name for "PURE / Alloy" 

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#14]

**Comment by brooklynrob** [comment]
Initial list of candidate names developed by @dintrator presented to GS on December 13, 2019. Now awaiting feedback.

**Comment by maoo** [comment]
@brooklynrob , can you please give us a status update on this? Do we have a final name?

**Comment by maoo** [comment]
All done here, marking as closed

**Comment by brooklynrob** [comment]
Done. Chosen. CC @pierredebelen
