### ISSUE TITLE
Commodity Reference Data Meeting - June 24th 2020

### ISSUE THREAD

**Issue by aitana16** [finos/alloy#170]
## Date
24 JUN 2020 - 11am ET / 4pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call
- [ ] Continuation of discussion of how to represent Benchmark v Physical  Commodities in Underlier model
- [ ] AOB, Q&A & Adjourn

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=me57eb4b2609b694befaaaf62c107f7e0
- Meeting number: 667 751 733
- Password: M4SiJxsth47
- Join by video system: Dial 667751733@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 667 751 733

**Comment by aitana16** [comment]
present!

**Comment by brooklynrob** [comment]
I'm here.

**Comment by astonGS** [comment]
Present

**Comment by nigelcobb** [comment]
Present

**Comment by ElaineFraser** [comment]
present

**Comment by kenneth-hei** [comment]
Present

**Comment by TSanborn-ISDA** [comment]
Here - thanks!
