### ISSUE TITLE
FX Options WG meeting - June 25th 2020

### ISSUE THREAD

**Issue by aitana16** [finos/alloy#172]
## Date
25 JUN 2020 - 12pm ET / 5pm BST

## Untracked attendees
- Ruddy Vincent / ISDA
- Illit Geller / Capitolis
- Michelangelo de Marzio / ISDA
- Ian Sloyan / ISDA
- Craig Rowe / Cantor Fitzgerald
- Rajesh Taparia / RBC

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] 1. Currency Ref Data Update - Vijay
- [ ] 2. Novations Analysis - Ted
- [ ] AOB, Q&A & Adjourn (5mins)

### Summary of Discussion
- _Currency Ref Data_: ongoing discussions in creating a solution to standardise currency reference data. Biweekly separate forum being put together for this by Finos. 
- _Novations_: Ted took the group through how novations are represented in the CDM model where the group also looked into a JSON example. Modelling of Parties is such that they can be referenced in any type of event, therefore specific delineation of e.g. _stepIn/Out parties_ is not required. Instead a party 'status/info' can be inferred from the message structure itself. No objections raised to current state of CDM modelling for novations.

### Next Steps
- Group has reviewed events including exercises, partial terminations and novations from a CDM lens, and now to review via Studio.

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m9989b4e8a8a07ed8677e35cf4bb879cd
- Meeting number: 667 055 449
- Password: CWfvDt6yA36
- Join by video system: Dial 667055449@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone: +1-415-655-0003 US Toll |  +44-20319-88141 UK Toll | Access code: 667 055 449

**Comment by TSanborn-ISDA** [comment]
Ted present at meeting on 25-Jun

**Comment by aitana16** [comment]
Here!

**Comment by brooklynrob** [comment]
I'm here.

**Comment by AJ73** [comment]
I am here

**Comment by harry-mcallister-bnpp** [comment]
In attendance.
