### ISSUE TITLE
July 1st, 2020 Alloy Bi-weekly Pilot Meeting

### ISSUE THREAD

**Issue by aitana16** [finos/alloy#173]
## Date
JUL 1 2020 - 12:30pm

## Approve past meeting minutes
- [June 17th meeting minutes ](https://github.com/finos/alloy/blob/master/meeting-minutes/pilot-project-meeting-minutes/2020.6.17-pilot-project-minutes.md) - _meeting minutes were approved_

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] FX Options WG update (Vijay Chandel)
- [ ] Commodities Reference Data WG update (Shaun Aston)
- [ ] AOB, Q&A & Adjourn 

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php MTID=m9faeb59f9167a188a0cde9a2209b9447
- Call-in:  +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Meeting number: 665 309 471
- Password: TAtaZkmC

**Comment by aitana16** [comment]
hi!

**Comment by TSanborn-ISDA** [comment]
Here!

**Comment by GeorgSchneider** [comment]
Hello world!

**Comment by nigelcobb** [comment]
hi

**Comment by astonGS** [comment]
Here

**Comment by sergiolopessp** [comment]
here

**Comment by beekemarie** [comment]
hi

**Comment by rsiddharthan** [comment]
Hi

**Comment by Vijayesh-Chandel** [comment]
Here

**Comment by gs-bracej** [comment]
Hi

**Comment by brooklynrob** [comment]
I am (was) here.
