### ISSUE TITLE
Jul 1 2020 Alloy Commodity Reference Data WG Meeting

### ISSUE THREAD

**Issue by ffionwiggins** [finos/alloy#174]
## Date
Jul 1 2020 - 11am EST

## Approve past meeting minutes
- [June 24th Meeting Minutes](https://github.com/finos/alloy/issues/170) 

## Untracked attendees
- Irina Yermakova / ISDA
- 

## Agenda
- [] Agree on definition of transactional vs product data and look to apply that onto the commodities products
- [] Discussion on what other data types could be included in product model

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=me57eb4b2609b694befaaaf62c107f7e0
- Meeting number: 667 751 733
- Password: M4SiJxsth47
- Join by video system: Dial 667751733@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll| Access code: 667 751 733

**Comment by aitana16** [comment]
Present!

**Comment by nigelcobb** [comment]
Present

**Comment by TSanborn-ISDA** [comment]
Cheers!

**Comment by kaurma-Manveen** [comment]
present

**Comment by brooklynrob** [comment]
I am (was) here.
