### ISSUE TITLE
Aug 20 2020 Alloy Monthly General Meeting

### ISSUE THREAD

**Issue by aitana16** [finos/alloy#178]
## Date
Aug 20 2020 - 9am ET / 2pm BST

## Untracked attendees
- Ffion Wiggins / GS
- Stephen Sui / RBC 
- Rajesh Taparia / RBC
- Paul Tilley / Deutsche Bank
- Ruddy Vincent / ISDA
- Hugo Hills / Regnosys
- Martin Gilbey / Thomson Reuters
- Mandy Darnell / Starburst
- Jim LeVan / Starburst
- Richard Wagener / Codethink

## Agenda
- [x] Convene & roll call (5mins)
- [x] Approve [June 18th Meeting minutes](https://github.com/finos/alloy/blob/master/meeting-minutes/general-meeting/2020.6.18-general-meeting.md) - _meeting minutes were approved_
- [x] Update on Alloy Pilot 
  - [x] FX Options [Vijayesh Chandel]
  - [x] Commodity Reference Data [Shaun Aston]
  - [x] ISDA [Ted Sanborn]
- [x] Open sourcing: next steps [Rob Underwood]
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m753c908a1d72885157b5deb7eeccea1c
- Password: 39BZdWsm
- Meeting number: 665 097 100
- Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 665 097 100
- Join by video system: Dial 665097100@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.

**Comment by adamj-codethink** [comment]
Hello o/

**Comment by brooklynrob** [comment]
Good morning

**Comment by stephengoldbaum** [comment]
ciao

**Comment by gcampbell-sl** [comment]
Hello.

**Comment by tonimcderment** [comment]
Hi

**Comment by urbanfletch** [comment]
Good morning all.

**Comment by Vijayesh-Chandel** [comment]
Hi!

**Comment by astonGS** [comment]
Hi

**Comment by TSanborn-ISDA** [comment]
Good morning!

**Comment by toshaellison** [comment]
hi

**Comment by RichardWagener365** [comment]
hi

**Comment by junjikatto** [comment]
Hello!!!

**Comment by aitana16** [comment]
hi!
