### ISSUE TITLE
Upgrade Gitlab to v12.10.12

### ISSUE THREAD

**Issue by maoo** [finos/alloy#180]
The following GitLab release have been released today and we should upgrade, see https://about.gitlab.com/releases/2020/05/27/security-release-13-0-1-released/

**Comment by gs-bracej** [comment]
I dont think we're ready to upgrade to v13, but we're running 12.10.12 internally so we should be able to apply the security patch.

**Comment by maoo** [comment]
I've updated the title to update to 12.10.x (currently 12.10.14).

Current GitLab server version is 12.10.1 

@gs-bracej - could you please confirm that 12.10.x is compatible with your APIs? TY!

**Comment by gs-bracej** [comment]
12.10.12 is as far as we've tested so far.

**Comment by maoo** [comment]
I've scheduled this activity for Friday morning (10am - 1pm CEST).

@gs-bracej - are you ok with this timing?

@aitana16 - could you please reach out to the WGs and the general Alloy group and communicate we may have downtimes during the mentioned timeframe? Please provide email lists I should notify when things go back to normal

@nuritzi - any chance that GitLab Support is available in that timeframe?

Thanks!

**Comment by gs-bracej** [comment]
Works for me!

**Comment by aitana16** [comment]
Done @maoo. I've [notified the alloy-pilot mailing list](https://groups.google.com/a/finos.org/forum/#!topic/alloy-pilot/SvJ1YlpbULU). The Alloy **general** list does not need to be notified as only pilot participants have access to the alloy gitlab instance.

**Comment by maoo** [comment]
All done, GitLab is updated to 12.10.12 version.

Steps performed:
```
sudo yum install gitlab-ee-12.10.12
sudo gitlab-rake db:migrate
sudo gitlab-ctl restart
```
