### ISSUE TITLE
Upload Alloy Studio Code

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#184]

**Comment by brooklynrob** [comment]
@maoo to work with @gs-bracej determine where the code will go when GS is ready and what the process will be to upload the code. Likely will need to be submitted via a GS-OSS process.

**Comment by brooklynrob** [comment]
First PR made -- https://github.com/finos/legend-studio/pull/2

**Comment by maoo** [comment]
Code is uploaded, closing issue.
