### ISSUE TITLE
FINOS Code Scans, Checks, Validation - Alloy Studio

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#185]
Starting this is dependent on https://github.com/finos/alloy/issues/184 completing (i.e., code being uploaded)

## Studio
- [x] FINOS Security Vulnerability Check
- [x] FINOS Legal/License Scans
- [x] Apply FINOS Project Blueprint

**Comment by brooklynrob** [comment]
Depends on https://github.com/finos/alloy/issues/184 to have completed before this can start.

**Comment by brooklynrob** [comment]
@maoo As suggested, I think these items can/should also appear on the FINOS infra kanban.

**Comment by gs-bracej** [comment]
These should all be resolved now. Please could you confirm and close?

**Comment by maoo** [comment]
Scan is passed, closing issue.
