### ISSUE TITLE
GS Internal Legal & Compliance Checks of Studio Code

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#188]
- [ ] GS Legal: Code Scanning and Releasing
- [ ] GS Legal: Contract License Agreement for IP Transfer

**Comment by brooklynrob** [comment]
Internal to GS the request to legal has been made. (2020.7.21)

**Comment by brooklynrob** [comment]
Per update on 2020.9.16 from @beekemarie and @gs-bracej, scope of what will open sourced within Studio has been reduced.

**Comment by brooklynrob** [comment]
@gs-bracej @beekemarie @pierredebelen  (CC @maoo @aitana16) Given the PRs (https://github.com/finos/legend-studio/pull/2) - yay! - can we assume this has been completed and can be closed?

**Comment by gs-bracej** [comment]
Yes!
