### ISSUE TITLE
08 05 2020 Alloy Monthly Pilot Meeting

### ISSUE THREAD

**Issue by aitana16** [finos/alloy#195]
## Date
08/05/2020 - 12.30pm ET/ 5.30pm BST

## Approve past meeting minutes
* Approve [July 1st meeting minutes](https://github.com/finos/alloy/issues/173) - _meeting minutes were approved_

## Untracked attendees
- Harry McAllister / BNP Paribas
- Ian Sloyan / ISDA

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Walkthrough of new Studio features - GS
- [ ] Feedback on modeling efforts to date. - GS 
- [ ] [Financial Objects RFC](https://github.com/finos/finos-fo/issues/38) - FINOS
- [ ] Training and Rollout plan - FINOS
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php MTID=m9faeb59f9167a188a0cde9a2209b9447
- Call-in:  +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Meeting number: 665 309 471
- Password: TAtaZkmC

**Comment by brooklynrob** [comment]
I'm here

**Comment by jonnance** [comment]
Hi - Here as well

**Comment by junjikatto** [comment]
Hi there

**Comment by GeorgSchneider** [comment]
Present

**Comment by nigelcobb** [comment]
present

**Comment by gs-bracej** [comment]
present

**Comment by astonGS** [comment]
Present

**Comment by aitana16** [comment]
present

**Comment by ffionwiggins** [comment]
I'm here

**Comment by stephengoldbaum** [comment]
hi

**Comment by TSanborn-ISDA** [comment]
Hello.

**Comment by erictice** [comment]
I am here
