### ISSUE TITLE
FX Options WG meeting - August 6th 2020

### ISSUE THREAD

**Issue by Vijayesh-Chandel** [finos/alloy#196]
## Date
August 6th 2020 - 12pm ET / 5pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] 1. Averaging Model Design - Vijay (15mins)
- [ ] 2. Trigger Model Design - Vijay (15mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Summary of Discussion
- _Averaging Model_: WG further reviewed the proposed modelling, and suggested the following changes which will be incorporated:
      - Instead of _OptionExercise_, rate averaging to be modelled as part of _OptionFeature_ class by adjusting the existing _Asian_ property within it
      - Removal of boolean _IsAveraged_ properties (and constraint) given averaging can be inferred from the presence of the AveragingObservation
      - Calculation/Function would be required for evaluating weights when dates are parametric. Calculations/Functions in general are beyond FpML architecture and ISDA will review on feasibility for CDM to accommodate these. Placeholder to be added in model proposal in the meantime

   Averaging Model Alloy Studio link: https://alloy.finos.org/studio/review/UAT-34/79
Note - AdjustableRelativeOrPeriodicDates and PeriodicDates classes already exist in CDM Rosetta but are yet to be fully ingested into Alloy Studio, hence for the purposes of the model proposals these classes have been created in the review (as per their respective CDM Rosetta design).

- _Trigger Model_: WG agree on asset class agnostic nature of a Trigger class. For FX specific features an ad-hoc meeting to be set up to discuss FX documentation standards which could help define the model for an FxObservable that could be re-used across the Trigger Model and the Averaging Model.

## Action Items
- [ ] Action 1: Incorporate suggested changes to the Averaging Model - Vijay
- [ ] Action 2: Arrange ad-hoc meeting on Fx Documentation Standards - Vijay/Aitana

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.phpMTID=m9989b4e8a8a07ed8677e35cf4bb879cd
- Meeting number: 667 055 449
- Password: CWfvDt6yA36
- Join by video system: Dial 667055449@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 667 055 449

**Comment by aitana16** [comment]
hi!

**Comment by AJ73** [comment]
hi

**Comment by TSanborn-ISDA** [comment]
hi

**Comment by cr20ro20** [comment]
Hi from Craig Rowe at Cantor Fitzgerald

**Comment by Vijayesh-Chandel** [comment]
### Untracked attendees
- Ian Sloyan / ISDA
