### ISSUE TITLE
FX Options WG meeting - August 13th 2020

### ISSUE THREAD

**Issue by Vijayesh-Chandel** [finos/alloy#198]
## Date
August 13th 2020 - 12pm ET / 5pm BST

## Approve past meeting minutes - #196 
- _Meeting minutes were approved_

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Averaging Model Review and Submission - Vijay (20mins)
- [ ] WG Close - Vijay (10mins)
- [ ] AOB, Q&A & Adjourn (5mins)

## Summary of Discussion
- _Averaging Model_: WG renamed property 'observationNumber' to 'observationReference' with type string and agreed with the final Averaging Model design. Testing of the model was demo'd, and has now been executed successfully with the removal of 'observationNumber' constraint which was controlling the property to be greater than zero. However given the property has now been changed from integer to string, this constraint no longer applies.

   **Averaging_Model Studio submission agreed by WG:** https://alloy.finos.org/studio/review/UAT-34/85
  _**Stage 3 milestone achieved**._
   - Submission includes an Averaging Model package containing model diagram, test results, target test class and notes
   - Notes contain placeholders for future design enhancements as suggested by the WG:
      - Placeholder - function to evaluate weights for parametric dates required in ObservationDates class. ISDA to review CDM feasibility for such functions
      - Placeholder - refactoring FxRateObservable in future. Provisions within FxDisruption FpML class (within FxSingleLeg) to be reviewed so to design a harmonized FxRateObservable that can be re-used
      - Placeholder - qualification function constraint which would determine when fxRateObservable is applicable
      - Additionally noted the Strike property definition refers to Credit only and is to be updated by ISDA
 
- _FX Pilot Close_: WG arrived to a successful completion. Additional ad hoc session will be arranged for open Stage 2 submission which is pending Studio 'Functions' feature upgrade (details: https://github.com/finos/alloy/issues/179). 

## Action Items
- [ ] Action 1: WG to approve the above Averaging Model submission and have merged into CDM model.

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.phpMTID=m9989b4e8a8a07ed8677e35cf4bb879cd
- Meeting number: 667 055 449
- Password: CWfvDt6yA36
- Join by video system: Dial 667055449@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 667 055 449

**Comment by aitana16** [comment]
hi!
