### ISSUE TITLE
Changes to Alloy Pilot ACLs on GitLab projects when open sourcing

### ISSUE THREAD

**Issue by maoo** [finos/alloy#204]
When Alloy becomes open source, the following changes will be applied to the Alloy pilot instance ACL
- [x] https://gitlab.alloy.finos.org/alloy-pilot/cdm will be publicly browsable (no GitLab account needed to see the models code)
- [x] https://gitlab.alloy.finos.org/alloy-pilot/commonrefdata will be publicly browsable
- [x] https://gitlab.alloy.finos.org/alloy-pilot/scratch will be publicly browsable

The rest of ACL configurations, both on GitLab and on Alloy Studio, will stay unchanged.

@gs-bracej @brooklynrob - could you please review and confirm?

**Comment by maoo** [comment]
@gs-bracej - can you please review this issue and confirm this is something we're comfortable to do, and no task is missing? TY!

**Comment by gs-bracej** [comment]
I don't mind this, my only questions are:
- Is there any reason from a security perspective we shouldn't open our GitLab to the whole world? Possibly we need someone from GitLab to confirm that our instance is sufficiently hardened for this, that there are other GitLab EEs open to all, and that our version has no known vulnerabilities?
- Does this have any affect on our GitLab license? I hope not but you never know.

**Comment by maoo** [comment]
Good questions @gs-bracej . I think I have some answers, but I'd rather let @gl-jayo answer, as he's the field expert on GitLab. Thanks!

**Comment by gl-jayo** [comment]
Hi @gs-bracej! Hi @maoo!

Having GitLab open to public browsing is great and should be secure ( and as far as I know, it's actually a requirement of the [GitLab Open Source Program](https://about.gitlab.com/handbook/marketing/community-relations/opensource-program/#who-qualifies-for-the-gitlab-for-open-source-program) cc: / @nuritzi ) 

From a security perspective it looks like you already doing the right things with the ports - port `80` and `443` are open - and I didn't notice any other ports open from a quick `nmap` scan. 

Also, You already have a default of controlling the visibility on projects - e.g. I don't see any projects as an unauthenticated user at https://gitlab.alloy.finos.org/explore - I am assuming you'll open those up on a case-by-case basis.

Other than staying up on the latest security patch release for the version you are using, and staying within the [Release and Maintenance Policy](https://docs.gitlab.com/ee/policy/maintenance.html) - especially:

> Backporting security fixes to the previous two monthly releases in addition to the current stable release - so staying within the last three months of `major.minor` releases will be key to keep getting security patches.

See also our May blog post on [GitLab Instance Security Best Practices](https://about.gitlab.com/blog/2020/05/20/gitlab-instance-security-best-practices/)

What you do absolutely want to review from a security and licensing perspective are your [Sign-Up](https://docs.gitlab.com/ee/user/admin_area/settings/sign_up_restrictions.html) restrictions.  

I've never tried logging into to https://gitlab.alloy.finos.org - but I am assuming that authentication/accounts are locked down at the moment with your integration with GitHub authentication - if so - great! You already have what you need there!

**Comment by maoo** [comment]
Great insight, thanks @gl-jayo ; I've created https://github.com/finos/alloy/issues/237 and I'll make sure to work on it ahead of the launch date.
