### ISSUE TITLE
09 02 2020 Alloy Commodity Reference Data WG

### ISSUE THREAD

**Issue by astonGS** [finos/alloy#212]
## Date
08 19 2020 - 16:00 BST

## Approve past meeting minutes
- Minutes Approved

## Agenda
- FixedPriceLeg Changes: Proposed representation as type of ForwardPayout
- Proposed Alterations to the CommodityPayout
- ISDA ARC - Proposal Date

Discussion Points:

The group discussed the options in which the FixedPriceLeg could be represented in the CDM. The proposed option that was included in Alloy Studio on the call leveraged the existing ForwardPayout and split it out into a FixedForward to cover the use case in question. On the call a point was raised that Cashflow is another possible alternative & the group will think on these 2 option before making a decision next week. 

On the second agenda point, the group discussed the naming conventions that could be considered for the 'commodity' payout, with a suggestion of AveragePayout given due to the terms that are included in the payout are not commodity specific and could in theory use to create a payout on another type of underlier. Additionally there was was similar suggestion on the naming of AssetPayout, which would potentially be more suitably called 'PerformancePayout'. Again, on these 2 points the group will meet next week and agree on best approach. 

The group aim is to agree finalized proposal in next weeks session with the plan to get in front on the ISDA ARC on October 6th. 

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=me57eb4b2609b694befaaaf62c107f7e0
- Meeting number: 667 751 733
- Password: M4SiJxsth47
- Join by video system: Dial 667751733@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
- Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll| Access code: 667 751 733

**Comment by thefarleyfan** [comment]
Present

**Comment by aitana16** [comment]
hi!

**Comment by nigelcobb** [comment]
present

**Comment by aitana16** [comment]
## Approve past meeting minutes

## Untracked attendees
Irina Yermakova / ISDA 
Kenneth Poon / GS
Jing Woo / GS
Nigel Cobb / Regnosys
Ted Sanborn / ISDA

**Comment by TSanborn-ISDA** [comment]
Hi - and thanks!
