### ISSUE TITLE
Test build and deploy works in open source environment for Shared library

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#217]
Test build and deploy works in open source environment for Shared library

**Comment by brooklynrob** [comment]
Per @maoo as of 2020.9.16, legend-shared build is green https://github.com/finos/legend-shared/runs/1123937816 

![image](https://user-images.githubusercontent.com/2136904/93386115-35ee8280-f835-11ea-8855-f62f6afdcead.png)

**Comment by brooklynrob** [comment]
[2020.9.21]: Per @maoo, "Build, test, and release pipeline successfully tested. Pending release from GS dev team and artifact consumption". CC @gs-bracej

**Comment by gs-bracej** [comment]
Release build is done and has been successfully consumed in GS.

**Comment by brooklynrob** [comment]
sweet! great stuff.
