### ISSUE TITLE
Upload Alloy PURE Code

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#223]
Dependent on https://github.com/finos/alloy/issues/222

**Comment by brooklynrob** [comment]
@maoo when you get a chance could you double check that the PURE repo is good to go including secrets (which I think @mindthegab took care of also w/ Engine and SDLC yesterday) https://github.com/finos/legend-pure

**Comment by maoo** [comment]
Code is uploaded. Closing issue.
