### ISSUE TITLE
FINOS Code Scans, Checks, Validation - PURE Code

### ISSUE THREAD

**Issue by aitana16** [finos/alloy#229]
This task dependent on https://github.com/finos/alloy/issues/223 completing. 

## Pure
- [ ] FINOS Security Vulnerability Check
- [ ] FINOS Legal/License Scans
- [ ] Apply FINOS Project Blueprint

**Comment by brooklynrob** [comment]
In progress as of 2020-10-8. @maoo has submitted a PR to address the first set of Whitesource issues found (https://github.com/finos/legend-pure/pull/9) and @swinslow has done an initial Fossology scan.

**Comment by aitana16** [comment]
Working with @maoo he agreed that this issue can be closed.
