### ISSUE TITLE
Upload Engine Code

### ISSUE THREAD

**Issue by aitana16** [finos/alloy#231]
This is dependent on https://github.com/finos/alloy/issues/230 being completed (i.e., GS being done its internal checks)

**Comment by brooklynrob** [comment]
@maoo Can you double check that https://github.com/finos/legend-engine is GTG for upload, including the setup of the secrets? I think it is, but please double check.

**Comment by brooklynrob** [comment]
Current ETA for upload is 2020-10-8 or 2020-10-9 per @pierredebelen

**Comment by aitana16** [comment]
Working with @maoo he agreed that this issue can be closed.
