### ISSUE TITLE
FINOS Code Scans, Checks, Validation - SDLC Code

### ISSUE THREAD

**Issue by aitana16** [finos/alloy#236]
This task can't start until https://github.com/finos/alloy/issues/235 is completed. 

## SDLC
- [x] FINOS Security Vulnerability Check
- [x] FINOS Legal/License Scans
- [x] Apply FINOS Project Blueprint

**Comment by finos-admin** [comment]
First FINOS scanning done, feedback provided by email

**Comment by maoo** [comment]
Feedback integrated, dashboards are clean, validation is passed!
