### ISSUE TITLE
Live upgrade assistance session with GitLab support for upcoming launch

### ISSUE THREAD

**Issue by nuritzi** [finos/alloy#239]
### Details
We'd need to do some operations on gitlab.alloy.finos.org for the open sourcing announcement of the Alloy project, which is planned on Tuesday 29 September.

We'd like to have the presence of GitLab to address any possible issue that occurs in such a time-sensitive activity, although we don't expect any complication.

We'll probably plan the GitLab config update as the first activity, so I don't expect more than 30 minutes for you.

#### The tasks to perform are

- [ ] Communicate to the Alloy Pilot participants that alloy.finos.org/studio will be down for a certain amount of time
- [ ] GitLab Upgrade, see https://github.com/finos/alloy/issues/237
- [ ] Update configuration to serve `gitlab.<newname>.finos.org` instead of gitlab.alloy.finos.org
- [ ] Renew SSL certificates for the new name
- [ ] Make sure that API endpoints are working properly

**Comment by maoo** [comment]
All done!
