### ISSUE TITLE
Add SonarCloud badges to all module repository's README.md files

### ISSUE THREAD

**Issue by maoo** [finos/alloy#243]
At the bottom right corner of SonarCloud project dashboard, there's a `Get project badges` button. There's quite a long list of badges that can be added. @gs-bracej , which ones you think would make most sense to report (see screenshot below)?

<img width="537" alt="Screenshot 2020-10-01 at 16 55 41" src="https://user-images.githubusercontent.com/327285/94826011-28292780-0407-11eb-8260-ccaa32285199.png">

When decided, it would be good to add these badges across all project repositories.

**Comment by gs-bracej** [comment]
Done for shared and studio, will do for SDLC when we have a successful Sonar report.
