### ISSUE TITLE
Reset Git history of shared and alloy repos

### ISSUE THREAD

**Issue by maoo** [finos/alloy#251]
Shared and Alloy repositories have collected a number of commits that bloat the git history.

After the website go-live, we should smash the git history into one single comment, with something along the lines of:

"Initial contribution of <newname> to FINOS" . @gs-bracej will sign the commits.

**Comment by aitana16** [comment]
@gs-bracej thinks we should reflect the reality of this project, leave the git history as is, and close this issue. It can be reopened if needed.

**Comment by brooklynrob** [comment]
I agree(d) with @gs-bracej -- I'm glad we're keeping the history and reflecting the reality of what's transpired to date on this effort.
