### ISSUE TITLE
New name logo misaligned on IphoneX + Safari

### ISSUE THREAD

**Issue by mindthegab** [finos/alloy#259]
See screenshot:

![IMG_CC2FAC4FD744-1](https://user-images.githubusercontent.com/961272/96321422-34e27980-0fca-11eb-90a2-5f687284dafd.jpeg)

**Comment by maoo** [comment]
@beekemarie @nicoalba @grizzwolf - can we try to find out if there's a simple fix we can apply for this bug? I expect many people using iPhones to check our page on Monday.

TY!

**Comment by maoo** [comment]
Should be fixed by https://github.com/finos/alloy/pull/261 . Tested successfully on iPhone emulator (chrome). @mindthegab - could you please check again? TY!

**Comment by maoo** [comment]
Fixed.
