### ISSUE TITLE
draft updated version of https://www.finos.org/pure-alloy

### ISSUE THREAD

**Issue by aitana16** [finos/alloy#43]
@grizzwolf and @aitana16 to draft updated version of https://www.finos.org/pure-alloy that will go live when the documentation page goes live (consider developer.gs.com to ensure they're aligned and to avoid duplicated content)

**Comment by maoo** [comment]
@aitana16 and @grizzwolf will start working this week on this.

**Comment by aitana16** [comment]
hi @grizzwolf adding the specific action items discussed on our call earlier today below:
- [ ] add link to the documentation site: https://alloy.finos.org/
- [ ] add this Question to the FAQ section: "What's the modeling scope of the pilot project?"
_Answer_: The current modeling scope encompasses an effort to extend FX options from ISDA's CDM model. Additional areas being discussed include CML Reference data, an RFQ in the context of interest rate swaps and ESG data. 
- [ ] harmonize timelines: Phase 1 should be "Q1-Q2 2020" instead of Q1 2020

**Comment by brooklynrob** [comment]
@aitana16 I've started to make the edits listed above that we discussed last week (see https://app.hubspot.com/content/2419532/edit/20928950602/content). FYI that I think the timeline on the Alloy documentation site also should get updated to reflect that Phase 1 is from January 2020 to May 2020.

**Comment by brooklynrob** [comment]
@aitana16 @grizzwolf I've made this edits -- can one of you review to check if I didn't catch any typos. See https://www.finos.org/alloy.

@aitana16 When you get a chance can you now update the alloy.finos.org site to match the timeline -- see how I've just used the quarters instead.

**Comment by aitana16** [comment]
@brooklynrob I've tried to make some edits here https://app.hubspot.com/content/2419532/edit/20928950602/content  but my current configuration does not allow me to save edits to landing pages. / cc @grizzwolf 

Specifically, the answer to the last question says that the next general meeting is set for **february 20th**. Instead of posting specific dates, and having to update them constantly, I'd redirect to the FINOS Programs Calendar https://calendar.google.com/calendar/embed?src=finos.org_fac8mo1rfc6ehscg0d80fi8jig%40group.calendar.google.com&ctz=America%2FNew_York
