### ISSUE TITLE
Publish CLA requirement on Docs site (alloy.finos.org)

### ISSUE THREAD

**Issue by aitana16** [finos/alloy#45]

**Comment by brooklynrob** [comment]
Once we have the first draft of the updated doc site from GS, we need to an overview of the CLA requirement to that documentation.

**Comment by brooklynrob** [comment]
This issue can and should be close once the link is added on the microsite to .github/CONTRIBUTING.md (https://github.com/finos/alloy/issues/69)

**Comment by maoo** [comment]
Done!
