### ISSUE TITLE
Document SDLC and contribution process for Pilot

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#60]
Several of the participating pilot banks have asked for a diagram and/or technical documentation such that they could better understanding how the SDLC works, and in particular how contributions and actual underlying git commits work into the hosted GitLab instance beneath the interactive layer of Alloy Studio. One motivation for needing these is to give to legal and compliance folks in these banks who are assessing risk and evaluating ability of contributors to use Alloy.

**Comment by maoo** [comment]
Diagram was created and shared with all interested parties.
