### ISSUE TITLE
Add link from alloy.finos.org docs site to .github/CONTRIBUTING.md

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#69]
1. Identify a place to add link to .github/CONTRIBUTING.md on alloy.finos.org
2. Add link

**Comment by gs-bracej** [comment]
I dont think files in the .github directory are published during the build, so we can't link to them. If that is true we'll need to move the file to the docs directory first.

@maoo please could you confirm or correct me here?

**Comment by maoo** [comment]
My idea was to add a build step that would copy the contents of .github/CONTRIBUTING.md into docs/contributing.md 

Keeping the same look 'n feel seems like the best solution. I've assigned the issue to me, it'll be ready next Monday/Tuesday; meanwhile, a `docs/contributing.md` file can be manually created by manually copying the contents.

**Comment by maoo** [comment]
See https://alloy.finos.org/docs/contribute
