### ISSUE TITLE
Finalize Agenda for 2020.2.12 Pilot Project Meeting

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#71]
See current draft at https://github.com/finos/alloy/blob/master/docs/meeting-minutes/2020.2.12-pilot-project-minutes.md

**Comment by brooklynrob** [comment]
Sounds like @johncoghlan is up for doing demo of the GitLab collaboration features.

**Comment by brooklynrob** [comment]
As a bit more context to the previous comment, at our weekly check-in today we discussed with @beekemarie and Ffi the need to for collaboration tools amongst the pilot project participants/modelers. Our working hypothesis is to take advantage of the GitLab collaboration tools and keep that modeling collaboration "close to the code" (i.e., the models) in gitlab.alloy.finos.org. (CC @johncoghlan @maoo @aitana16)

**Comment by johncoghlan** [comment]
Happy to showcase some of GitLab's collaboration features. Most of it will be very familiar to most folks who have used GitHub, JIRA, etc. so I don't think we'll be opening many eyes. Priority will be showing folks how to manage their GitLab profiles and settings to ensure they receive notifications in a way that will allow them to collaborate via email.

**Comment by brooklynrob** [comment]
@beekemarie have you had a chance to talk with @pierredebelen about what features he might want to demo tomorrow?

**Comment by beekemarie** [comment]
We are ready to give folks a first glance of the CDM model on the external instance of Studio. The rest of the demo can be driven by attendee interest/demand? So for the 12:30pm:

1) Update from FINOS on recent developments (Alloy website, getting people ready to start modeling, etc.)
2) Update from Ffi on Pilot Phase Management and "homework" for the next 2 weeks
3) CDM model & demo of features requested by audience

Sounds good?

**Comment by brooklynrob** [comment]
@aitana16 to close this issue you can you 1) upload the PDF of the deck from yesterday to the github and 2) write up the meeting minutes (in https://github.com/finos/alloy/blob/master/docs/meeting-minutes/2020.2.12-pilot-project-minutes.md), including adding a link to deck's location on github

**Comment by aitana16** [comment]
hi @brooklynrob , I have (1) uploaded the pdf deck and linked it to the meeting minutes, (2) added the attendee list to the 2/12 meeting minutes https://github.com/finos/alloy/blob/master/docs/meeting-minutes/2020.2.12-pilot-project-minutes.md 
Closing this issue now
