### ISSUE TITLE
Suggest Topics and Develop Agenda for 2020.2.20 Alloy General Meeting

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#73]

**Comment by aitana16** [comment]
hi @brooklynrob adding the agenda items discussed on this morning's call:

1. Recap demo of what Alloy is
2. Studio demo: Deep dive on SDLC and execution (@beekemarie to confirm
3. Show Pure/Alloy microsite
4. Update on the pilot project
5. Releasing of external instance to the pilot group by [date]
6. First pilot participants able to participate by [date]

**Comment by maoo** [comment]
@aitana16 - can this issue be closed?
