### ISSUE TITLE
Bug: Can't create stereotype values in pilot instance

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#74]
### Steps to Reproduce:
1. Create a class per documentation in https://alloy.finos.org/docs/getting-started/studio up to stereotype step
2. Navigate to `stereotype` tab
3. Attempt to create a stereotype of type `access` and with a value of `public`
 The type `access` appears

Conversely, if I try to add the type and value in code mode (`<<meta::pure::profiles::alloy.public>>` and click `F8` to switch back to interactive mode, the value disappears. If I hit `Ctrl-S` the code does not appear in the corresponding PURE JSON code in GitLab either.

### Expected Result:
Stereotype value is created and saved

### Actual Result:
Stereotype value is not created and saved

### Environment:
* Alloy Instance: alloy.finos.org/studio
* Project: `play`
* Branch (Workspace): `workspace/brooklynrob/dev`
* GitLab URL: https://gitlab.alloy.finos.org/brooklynrob/play/blob/workspace/brooklynrob/dev/entities/demo/Person.json
<img width="1308" alt="Screen Shot 2020-02-15 at 5 37 25 PM" src="https://user-images.githubusercontent.com/2136904/74596203-f7cc7e80-5019-11ea-906c-5a7c97c11f59.png">

### Questions
- Is this a problem with the instance? Or the docs?

**Comment by gs-bracej** [comment]
This looks like an artifact of the docs and deployed version being out of sync - it works on the latest version. Will retest after our next deployment.

**Comment by maoo** [comment]
@gs-bracej , did the new deployment happen? Or do you have an ETA?

**Comment by gs-bracej** [comment]
Sorry! Yes it happened, please could you retest to confirm its gone?

**Comment by brooklynrob** [comment]
Will test.

**Comment by maoo** [comment]
Just tested on my side. I cannot see anymore the `access` value for stereotypes, only `doc` and `typemodifiers`....

<img width="1507" alt="Screenshot 2020-03-17 at 15 23 14" src="https://user-images.githubusercontent.com/327285/76865602-3e083e00-6863-11ea-9e74-18bd74fdc54c.png">

@gs-bracej - is this the expected behaviour?

**Comment by gs-bracej** [comment]
Yes this is expected. Access stereotype doesnt make any sense in this env, so we've removed it for now.
