### ISSUE TITLE
Setup GitLab user permissions

### ISSUE THREAD

**Issue by maoo** [finos/alloy#77]
Do we want all users in gitlab.alloy.finos.org to access private and internal projects?

If not, we should check the `External Users` flag for each non-admin user (see screenshot)

<img width="1112" alt="Screenshot 2020-02-26 at 03 11 00" src="https://user-images.githubusercontent.com/327285/75305233-d2bfe300-5845-11ea-8cbe-0cf624cd5a51.png">

In order to provide project access to a wide group of users (ie, all pilot users), we can use Groups, there's already one called `Alloy-Pilot`. I suggest this group to be directly managed by @brooklynrob .

Is it ok if I flag all users as external? @gs-bracej  Are there any existing projects that should be already accessible by every Pilot user?

**Comment by gs-bracej** [comment]
+1. Flagging the users as external seems like a good idea to stop them creating their projects directly in GitLab, which we dont want at this point. 

I've added the two projects we want users to see (CDM and Scratch) to the Alloy-Pilot group. We will need to add new users as Developers in this group so they can access these projects. We should keep a small list of Maintainers who can approve the MRs.

**Comment by brooklynrob** [comment]
I agree with @gs-bracej. Let's turn that flag on.

**Comment by gs-bracej** [comment]
Do we have a canonical doc somewhere that describes the steps for onboarding users? The process has several steps that we don't want to miss:
- Setting up the link to their Github id
- Marking as external
- Adding to the Alloy-Pilot gruop

**Comment by finos-admin** [comment]
James, docs are on https://alloy.finos.org/docs/contribute ; can you please
check if anything is missing and update the text, if needed?

Also, I went ahead and marked everyone as External User.

Please note that me, James and Rob are the only admins and therefore those
who can add new users to the system.

Please remember - when creating a new user - to:

   1. Toggle the "External User" on
   2. Toggle the "Can create groups" off

Or just email help@finos.org with the request to add an Alloy user, I'll
take care of that.

Rob, I took the freedom to remove, from the Alloy-Pilot group, everyone
that was not covered by a CCLA; right now the Alloy-Pilot group only
contains Rob, James, Pierre and me.

James, you may want to add the "Alloy-Pilot" group as collaborators of the
GitLab projects you created last week.

Thanks!
  mao

>

**Comment by maoo** [comment]
To complete this task:
- [ ] Define group of approvers for each modeling project (James, FFi, Beeke, Pierre can be allocated to multiple projects). Approvers are defined via the "Merge Request Approval" project settings
- [ ] Define project lead, add as approval step
- [ ] Choose the group of maintainers (ie rob, James, mao, Pierre) who are the only ones able to merge a Merge Request, as project Maintainers; group is called "Alloy-maintainers" and will have "Maintainer" role across all projects
- [ ] Setup "Merge checks", "pipelines must succeed" on "Merge Requests" project configuration
- [ ] Stretch goal - define configurations at group level

- [ ] Setup test on user permissions: mao, James and Rob act as contributor, approver, maintainer and check scenarios where 1) CLA bot fails 2) approval doesn't pass 3) everything is good

**Comment by maoo** [comment]
Created #82 and #83 with related activities; closing this issue, as the GitLab Permissions aspect have been figured out and configured at (`Alloy-Pilot`) Group level .
