### ISSUE TITLE
Adding link to FINOS Privacy Policy

### ISSUE THREAD

**Issue by maoo** [finos/alloy#80]
The new GDPR-compliant privacy policy should replace the existing privacy policy on the FINOS website and anywhere else it's publicly available.

The link is added to the leftbar menu, below the "docs" path, with label "Finos Privacy Policy", pointing to https://www.finos.org/privacy-policy

A PR was tentatively raised, but didn't work (Docusaurus 1 doesn't allow external links on sidebars), see https://github.com/finos/alloy/pull/79

I've worked on a simple version for footer links, see http://blog.session.it/alloy/docs/contribute .  @gs-bracej @beekemarie - could you please pass this update to your designers and adapt it to the website visual guidelines?

Pull Request is on https://github.com/finos/alloy/pull/84

**Comment by maoo** [comment]
@gs-bracej @beekemarie - any update on this? Please let me know if we can help further. TY!

**Comment by gs-bracej** [comment]
Yep I have this ready to go, was waiting for my previous PR to complete. Will push this shortly.

**Comment by maoo** [comment]
Hi @gs-bracej , was this added to the live website already? If not, I wonder if adding an h2 item onhttps://alloy.finos.org/docs/get-involved/terms-of-service could be the right solution for now... after the pilot - if needed - we can make it more prominent. WDYT?

**Comment by gs-bracej** [comment]
Yep, here's a PR - https://github.com/finos/alloy/pull/85
