### ISSUE TITLE
Restrict access to clabot-config project to only maintainers

### ISSUE THREAD

**Issue by maoo** [finos/alloy#81]
The CLA Bot configuration is hosted on https://gitlab.alloy.finos.org/alloy-pilot/clabot-config and is currently accessible by every participant to the pilot.

Considering that the CLA Bot configuration includes the GitHub IDs of all participants, it would be best to restrict access to only Maintainers.

Note that GitHub IDs are publicly available via the GitHub User API, so this issue is not blocking for the Alloy Pilot.

Would be great to have the ability to configure GitLab project permissions to only allow view to Maintainers, but couldn't find a way to achieve it.

/CC @johncoghlan

**Comment by johncoghlan** [comment]
@maoo one potential solution: 

1. Create a group for the maintainers (i.e. folks you would like to have access to the clabot-config project)
1.  Move the clabot-config project into that group 
1. Make the clabot-config project private which will limit access to only members of the group 

Let me know if that solution works. If not, please schedule some time via the Calendly link I sent you via email so we can discuss alternative solutions.

**Comment by maoo** [comment]
Thanks @johncoghlan ; the problem with this solution is that the clabot-config project must reside in the same group of the rest of the projects, as this is the convention we built. We could potentially add another convention though, which tries to load a CLA bot configuration (to apply across the whole GitLab instance) from gitlab.alloy.finos.org/clabot/config , where "clabot" is a group and "config" is a project.

Unless there are explicit configurations to address the challenge, I could start working on this solution.

**Comment by maoo** [comment]
After discussing this with @johncoghlan , we agreed that this is not a battle that is worth fighting, considering that GitHub IDs of all FINOS contributors can already be (quite easily) extracted from metrics.finos.org .

Closing the issue.
