### ISSUE TITLE
Dry run of a change request via Alloy Studio

### ISSUE THREAD

**Issue by maoo** [finos/alloy#82]
Final testing and review with @brooklynrob and @gs-bracej of Alloy Pilot contribution process, using the Scratch project - https://gitlab.alloy.finos.org/alloy-pilot/scratch

- [x] Remove myself from the CLA Bot whitelist, see https://gitlab.alloy.finos.org/alloy-pilot/clabot-config/blob/master/.clabot
- [x] Configure "Pipelines must succeed" in "Merge checks" - this should prevent Alloy Studio to merge the change, if flagged by the CLA bot
- [x] Configure 2 approvals workflows in scratch: 1) lead (Rob) 2) working group (james)
- [x] Make a change to scratch and submit it via Alloy Studio UI
- [x] Verify that CLA bot commented the merge request, now it's on approval
- [x] Verify that Maintainers are not able to merge the change via Alloy Studio UI
- [x] Approve Merge Request
- [x] Update CLA Bot config and resummon bot
- [x] Commit request via Alloy Studio

**Comment by maoo** [comment]
Test done. I see that the Merge Request was created on https://gitlab.alloy.finos.org/alloy-pilot/scratch/merge_requests/3

![screencapture-gitlab-alloy-finos-org-alloy-pilot-scratch-merge-requests-3-2020-03-10-15_46_40](https://user-images.githubusercontent.com/327285/76324585-8b762f80-62e6-11ea-874f-49edbd3ccd80.png)

As you can see, I cannot merge the request, as the Pipeline have failed and the MR is pending approval.

However, in Alloy Studio, I can "Commit review". @gs-bracej - does this mean that I'm able (as Maintainer of the group) to merge it? Shouldn't the button be disabled?

![screencapture-alloy-finos-org-studio-UAT-33-scratch-workspace-2020-03-10-15_49_48](https://user-images.githubusercontent.com/327285/76324793-cbd5ad80-62e6-11ea-89f7-672732e20860.png)

**Comment by gs-bracej** [comment]
Studio doesnt have logic to disable the button, but if you try it you'll see an error (please do try it and confirm!)
I'll add an item to disable the button when necessary to the backlog...

**Comment by maoo** [comment]
And indeed, I got an error 👍 

<img width="1433" alt="Screenshot 2020-03-10 at 15 56 57" src="https://user-images.githubusercontent.com/327285/76325681-e2303900-62e7-11ea-865f-08f258880023.png">

Cool, let's proceed with the approval then, let's try to "fix" this request and make it committable.

@gs-bracej @brooklynrob - can you please approve https://gitlab.alloy.finos.org/alloy-pilot/scratch/merge_requests/3 ?

**Comment by gs-bracej** [comment]
I've added my approval, but you need others.

**Comment by maoo** [comment]
Others approved, CLA Bot resummoned. @gs-bracej , can you try to accept the change?

**Comment by maoo** [comment]
Just accepted the change via Alloy Studio, all worked as expected! Closing issue.
