### ISSUE TITLE
Define approvers for each modeling initiative (GitLab Project)

### ISSUE THREAD

**Issue by maoo** [finos/alloy#83]
**Tasks:**
- Define "Working Group" approval group (e.g 3)
- Define "Project lead" approval person
- Setup Merge Request approval process

**List of projects:**
- [x] Scratch
- [ ] CDM
- [ ] CMLRefData

**Comment by brooklynrob** [comment]
To set expectations I expect it'll be a couple more weeks at least before we identify the approvers. I think we need to get the respective working groups (FX Options and Commodities Reference Data) up and running first before we can decide what the right business rule is for approvers and who those approvers are. 

The two approval models - not mutually exclusive as I understand it - are 

- We define an amount (e.g. 3) of approvers who must sign off on a change
- We define 1 or more specific named users (e.g., @ffionwiggins) who must do an approval

CC @beekemarie @johncoghlan @gs-bracej @pierredebelen)

**Comment by maoo** [comment]
Configuration on scratch project done - https://gitlab.alloy.finos.org/alloy-pilot/scratch/edit

**Comment by maoo** [comment]
@brooklynrob - any update on this?
