### ISSUE TITLE
Create documentation of process to submit, approve, and merge a model change

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#88]
This is the documentation, to go on the [docs site](alloy.finos.org), to show the workflow from model change, to approval to, to merge to the master branch of a model change.

**Comment by aitana16** [comment]
pasting James' update from e-mail thread:

**Milestone 1 – Code uplift**
[ ] Relational mapping in Studio - _underway_
[ ] Relational execution and testing in Studio - _underway_
[ ] Execution refactor to remove GS connection management - _underway_
[ ] Extract core PURE System ready for Open sourcing

**Milestone 2 – Initial Code release** - _completion target: September 2020. Once Milestone 2 is completed, we can consider Alloy to be 'open sourced' and milestones 3 and 4 are rounding up the story_
[ ] Create external repos for Studio, Exec, System
[ ] Publish code for SDLC, Execution, Studio, PURE System
[ ] CI build + release process
[ ] Deploy pipeline from code to demo env

**Milestone 3 – docs completeness**
[ ] Video tutorials for Studio
[ ] Guide to building and deploying
[ ] Guide to developing in Alloy

**Milestone 4 – Remaining UIs**
[ ] Create external repos for Cube, Graph, Services
[ ] Publish code for Cube, Graph, Services
[ ] Add to demo env
[ ] Deploy demo database to demonstrate execution

**Comment by gs-bracej** [comment]
@aitana16, I suspect you might have mixed up tickets - not sure that list is relevant to this one.

Back on the original subject, @brooklynrob we do have docs for the SDLC process here - https://alloy.finos.org/docs/getting-started/sdlc. Do you think there are things missing?

Also cc @beekemarie in case we need docs improvements.

**Comment by aitana16** [comment]
hi @gs-bracej you're right, apologies for the confusion.

**Comment by maoo** [comment]
@beekemarie  @gs-bracej - I've reviewed the contents (sorry for the delay); it would be probably good to mention the CLA bot and what a reviewer should expect, in case checks fail. WDYT?

**Comment by brooklynrob** [comment]
Actually, it looks like most of this material is already in place at https://alloy.finos.org/docs/getting-started/sdlc 

What needs to be added is 
1) a sentence or two that states that it's up to each working group/modeling team to set their own approval process whether that's consensus (1+ other people need to weigh in), (a) designated approver(s), or some combination

2) show some basic screens about what the approver does and what the approval screens look like

3) describes the role of the merger (using going to be Mao or myself)

CC @gs-bracej @beekemarie

**Comment by brooklynrob** [comment]
If you'd like to at the work I'm starting to do to expand this page, check out the draft on my fork at https://brooklynrob.github.io/alloy/docs/getting-started/sdlc

**Comment by brooklynrob** [comment]
@gs-bracej would be interest to hear your feedback if this (https://brooklynrob.github.io/alloy/docs/getting-started/sdlc) is the direction you were thinking. Also, is their an approval step in Alloy itself (i.e., not in GitLab) we should add?

**Comment by aitana16** [comment]
thanks Rob for adding this information to https://alloy.finos.org/docs/getting-started/pilot-model-governance
